[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[build.nixpacksConfig]
buildCommand = "yarn install && yarn build"