[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.build]
cmds = [
    "cd frontend && npm ci && npm run build",
    "pip install -r requirements.txt"
]

[start]
cmd = "python backend/server.py"