# Nixpacks configuration for Railway deployment

[start]
cmd = "cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"

[phases.build]
cmds = [
  "cd backend && pip install -r requirements.txt"
]