[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments.production]
PYTHON_VERSION = "3.11"

[environments.production.variables]
PYTHONPATH = "/app/backend"